import type { FluidProperty, FluidPropertyConfig } from "./FluidTypes";

const propertyDefaults: Record<FluidProperty, FluidPropertyConfig> = {
    'f-width': { min: '100px', ideal: '35vw', max: '200px', enabled: false },
    'f-height': { min: '60px', ideal: '20vw', max: '100px', enabled: false },
    'f-font-size': { min: '1rem', ideal: '2.5vw', max: '2rem', enabled: false },
    'line-height': { min: '1.2', ideal: 'calc(1em + 1vw)', max: '2', enabled: false },
    'padding-top': { min: '0.4rem', ideal: '1vw', max: '0.8rem', enabled: false },
    'padding-right': { min: '0.5rem', ideal: '1.2vw', max: '1rem', enabled: false },
    'padding-bottom': { min: '0.4rem', ideal: '1vw', max: '0.8rem', enabled: false },
    'padding-left': { min: '0.5rem', ideal: '1.2vw', max: '1rem', enabled: false },
    'f-padding': { min: '0.5rem', ideal: '1.5vw', max: '1rem', enabled: false },
    'margin-top': { min: '0.4rem', ideal: '0.9vw', max: '0.8rem', enabled: false },
    'margin-right': { min: '0.5rem', ideal: '1.2vw', max: '1rem', enabled: false },
    'margin-bottom': { min: '0.4rem', ideal: '0.9vw', max: '0.8rem', enabled: false },
    'margin-left': { min: '0.5rem', ideal: '1.2vw', max: '1rem', enabled: false },
    'f-margin': { min: '0.5rem', ideal: '1.5vw', max: '1rem', enabled: false },
    'row-gap': { min: '0.5rem', ideal: '2vw', max: '1.5rem', enabled: false },
    'column-gap': { min: '0.5rem', ideal: '2vw', max: '1.5rem', enabled: false },
    'f-gap': { min: '0.5rem', ideal: '2vw', max: '1.5rem', enabled: false },
    'border-radius': { min: '0.25rem', ideal: '1vw', max: '1rem', enabled: false },
    'border-width': { min: '1px', ideal: '0.5vw', max: '5px', enabled: false },
    'f-top': { min: '0', ideal: '0', max: '0', enabled: false },
    'f-right': { min: '0', ideal: '0', max: '0', enabled: false },
    'f-bottom': { min: '0', ideal: '0', max: '0', enabled: false },
    'f-left': { min: '0', ideal: '0', max: '0', enabled: false },
    'f-inset': { min: '0', ideal: '0', max: '0', enabled: false },
};

const propertyToClassMap: Record<FluidProperty, string> = {
    'f-width': 'fluid-width',
    'f-height': 'fluid-height',
    'f-font-size': 'fluid-fs',
    'line-height': 'fluid-lh',
    'padding-top': 'fluid-pt',
    'padding-right': 'fluid-pr',
    'padding-bottom': 'fluid-pb',
    'padding-left': 'fluid-pl',
    'f-padding': 'fluid-p',
    'margin-top': 'fluid-mt',
    'margin-right': 'fluid-mr',
    'margin-bottom': 'fluid-mb',
    'margin-left': 'fluid-ml',
    'f-margin': 'fluid-m',
    'row-gap': 'fluid-rg',
    'column-gap': 'fluid-cg',
    'f-gap': 'fluid-gap',
    'border-radius': 'fluid-br',
    'border-width': 'fluid-bw',
    'f-top': 'fluid-top',
    'f-right': 'fluid-right',
    'f-bottom': 'fluid-bottom',
    'f-left': 'fluid-left',
    'f-inset': 'fluid-inset',
};

export { propertyDefaults, propertyToClassMap };